<?php
$schools = [
"Abbotts Creek ES",
"Adams ES",
"Alston Ridge ES",
"Alston Ridge MS",
"Apex ES",
"Apex Friendship HS",
"Apex Friendship MS",
"Apex HS",
"Apex MS",
"Athens HS",
"Aversboro ES",
"Baileywick ES",
"Ballentine ES",
"Banks Rd ES",
"Barwell ES",
"Baucom ES",
"Beaverdam ES",
"Brassfield ES",
"Brentwood ES",
"Briarcliff ES",
"Brier Creek ES",
"Brooks ES",
"Broughton HS",
"Bryan Road ES",
"Buckhorn Creek ES",
"Bugg ES",
"Carnage MS",
"Carpenter ES",
"Carroll MS",
"Carver ES",
"Cary ES",
"Cary HS",
"Cedar Fork ES",
"Centennial MS",
"Combs ES",
"Conn ES",
"Creech Road ES",
"Davis Drive ES",
"Davis Drive MS",
"Dillard Dr ES",
"Dillard Dr MS",
"Douglas ES",
"Durant Rd ES",
"Durant Rd MS",
"East Cary MS",
"East Garner ES",
"East Garner MS",
"East Millbrook",
"East Wake HS",
"Enloe HS",
"Farmington Woods",
"Forest Pines ES",
"Forestville Rd ES",
"Fox Road ES",
"Frankie Lemmon",
"Fuller ES",
"Fuquay-Varina ES",
"Fuquay-Varina HS",
"Fuquay-Varina MS",
"Garner HS",
"Green ES",
"Green Hope ES",
"Green Hope HS",
"Green Level HS",
"Harris Creek ES",
"Herbert Akins ES",
"Heritage ES",
"Heritage HS",
"Heritage MS",
"HighCroft ES",
"Hilburn Academy K-8",
"Hodge RD ES",
"Holly Grove ES",
"Holly Grove MS",
"Holly Ridge ES",
"Holly Ridge MS",
"Holly Springs ES",
"Holly Springs HS",
"Hortons Creek ES",
"Hunter ES",
"Jeffreys Grove",
"Jones Dairy ES",
"Jordan Center",
"Joyner ES",
"Kingswood ES",
"Knightdale ES",
"Knightdale HS",
"Lacy ES",
"Lake Myra ES",
"Laurel Park ES",
"Lead Mine ES",
"Leesville RD ES",
"Leesville RD HS",
"Leesville RD MS",
"Ligon MS",
"Lincoln HGHTS ES",
"Lockhart ES",
"Longview HS",
"Lufkin Road MS",
"Lynn Road ES",
"Martin MS",
"Middle Creek ES",
"Middle Creek HS",
"Millbrook ES",
"Millbrook HS",
"Mills Park ES",
"Mills Park MS",
"Moore Square MS",
"Morrisville ES",
"Mount Vernon School",
"Neuse River MS",
"North Forest Pines ES",
"North Garner MS",
"North Ridge ES",
"North Wake CCA",
"Northwoods ES",
"Oak Grove ES",
"Oakview ES",
"Oberlin MS",
"Olds ES",
"Olive Chapel ES",
"Panther Creek HS",
"Parkside ES",
"Partnership ES",
"Penny Road ES",
"Phillips HS",
"Pine Hollow MS",
"Pleasant Grove ES",
"Pleasant Union",
"Poe ES",
"Powell ES",
"Rand Road ES",
"Ray of Hope",
"Reedy Creek ES",
"Reedy Creek MS",
"Richland Creek ES",
"River Bend ES",
"River Bend MS",
"River Oaks MS",
"Rogers Lane ES",
"Rolesville ES",
"Rolesville HS",
"Rolesville MS",
"Root ES",
"Salem ES",
"Salem MS",
"Sanderson HS",
"Sanford Creek ES",
"Score Academy",
"Scotts Ridge ES",
"Smith ES",
"South Garner HS",
"Southeast Raleigh ES",
"Southeast Raleigh HS",
"Stough ES",
"Swift Creek ES",
"Sycamore ES",
"Timber Drive ES",
"Turner Creek ES",
"Underwood ES",
"Vance ES",
"Vandora SPRGS ES",
"Vernon Malone HS",
"Wake Early College HS",
"Wake Forest ES",
"Wake Forest HS",
"Wake Forest MS",
"WAKE NCSU STEM",
"Wake Young Mens LA",
"Wake Young Womens LA",
"Wakefield ES",
"Wakefield HS",
"Wakefield MS",
"Wakelon ES",
"Walnut Creek ES",
"Washington ES",
"Weatherstone ES",
"Wendell ES",
"Wendell MS",
"West Cary MS",
"West Lake ES",
"West Lake MS",
"West Millbrook",
"White Oak ES",
"White Plains",
"Wilburn ES",
"Wildwood Forest",
"Wiley ES",
"Willow Springs",
"Yates Mill ES",
"York ES",
"Zebulon ES",
"Zebulon MS"
];
